name: Release PR

on:
  push:
    branches:
      - main
  workflow_dispatch: # for manual release fixes
    inputs:
      retry-publish:
        description: "Retry publishing"
        type: boolean
        required: false
        default: false

permissions:
  contents: write
  pull-requests: write
  id-token: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: block/ospo/actions/releaser@main
        with:
          release-type: node
          node-version: 20
          npm-token: ${{ secrets.NPM_TOKEN }}
          package-manager: yarn
          retry-publish: ${{ inputs.retry-publish }}
          prepare-cmds: |
            yarn install --frozen-lockfile
            yarn lint
